AllCops:
  TargetRubyVersion: 2.2
  Include:
    - "**/*.rake"
    - Gemfile
    - Rakefile
    - Guardfile
  Exclude:
    - config/deploy.rb
    - "vendor/**/*"
    - db/schema.rb

Documentation:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/LiteralInInterpolation:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - db/migrate/*
    - test/**/*

Metrics/LineLength:
  Max: 120
  Exclude:
    - db/migrate/*
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
    - test/**/*

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AutoResourceCleanup:
  Enabled: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/FirstParameterIndentation:
  EnforcedStyle: special_for_inner_method_call

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - test/**/*
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Style/PredicateName:
#   Enabled: false

Style/Send:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
